<a href="https://colab.research.google.com/github/debasishghosh-lab/Seq2Seq-English-to-Bengali-Translator/blob/main/01_Seq2Seq_English_Bengali_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numerical computations
import numpy as np

# Deep Learning Framework
import tensorflow as tf

# Text preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Neural Network Layers
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

# Build the complete model
from tensorflow.keras.models import Model

In [ ]:
print("TensorFlow Version:", tf.__version__)
print("NumPy Version:", np.__version__)

TensorFlow Version: 2.20.0
NumPy Version: 2.0.2


In [ ]:
english_sentences = [
    "hello",
    "hi",
    "good morning",
    "good night",
    "goodbye",
    "thank you",
    "sorry",
    "please",
    "yes",
    "no",
    "how are you",
    "i am fine",
    "what is your name",
    "my name is debasish",
    "where are you",
    "come here",
    "sit down",
    "stand up",
    "open the door",
    "close the door"
]

bengali_sentences = [
    "হ্যালো",
    "হাই",
    "সুপ্রভাত",
    "শুভ রাত্রি",
    "বিদায়",
    "ধন্যবাদ",
    "দুঃখিত",
    "অনুগ্রহ করে",
    "হ্যাঁ",
    "না",
    "তুমি কেমন আছো",
    "আমি ভালো আছি",
    "তোমার নাম কী",
    "আমার নাম দেবাশীষ",
    "তুমি কোথায় আছো",
    "এখানে আসো",
    "বসো",
    "দাঁড়াও",
    "দরজা খোলো",
    "দরজা বন্ধ করো"
]

In [ ]:
decoder_bengali_sentences=[]

for words in bengali_sentences:
  decoder_bengali_sentences.append("<start> "+words+" <end>")

print(decoder_bengali_sentences)

['<start> হ্যালো <end>', '<start> হাই <end>', '<start> সুপ্রভাত <end>', '<start> শুভ রাত্রি <end>', '<start> বিদায় <end>', '<start> ধন্যবাদ <end>', '<start> দুঃখিত <end>', '<start> অনুগ্রহ করে <end>', '<start> হ্যাঁ <end>', '<start> না <end>', '<start> তুমি কেমন আছো <end>', '<start> আমি ভালো আছি <end>', '<start> তোমার নাম কী <end>', '<start> আমার নাম দেবাশীষ <end>', '<start> তুমি কোথায় আছো <end>', '<start> এখানে আসো <end>', '<start> বসো <end>', '<start> দাঁড়াও <end>', '<start> দরজা খোলো <end>', '<start> দরজা বন্ধ করো <end>']


In [ ]:
english_tokenizer=Tokenizer()
bengali_tokenizer = Tokenizer(
    filters='!"#$%&()*+,-./:;=?@[\\]^_`{|}~\t\n'
)
english_tokenizer.fit_on_texts(english_sentences)
bengali_tokenizer.fit_on_texts(decoder_bengali_sentences)

print(english_tokenizer.word_index)
print(bengali_tokenizer.word_index)

{'you': 1, 'good': 2, 'are': 3, 'is': 4, 'name': 5, 'the': 6, 'door': 7, 'hello': 8, 'hi': 9, 'morning': 10, 'night': 11, 'goodbye': 12, 'thank': 13, 'sorry': 14, 'please': 15, 'yes': 16, 'no': 17, 'how': 18, 'i': 19, 'am': 20, 'fine': 21, 'what': 22, 'your': 23, 'my': 24, 'debasish': 25, 'where': 26, 'come': 27, 'here': 28, 'sit': 29, 'down': 30, 'stand': 31, 'up': 32, 'open': 33, 'close': 34}
{'<start>': 1, '<end>': 2, 'তুমি': 3, 'আছো': 4, 'নাম': 5, 'দরজা': 6, 'হ্যালো': 7, 'হাই': 8, 'সুপ্রভাত': 9, 'শুভ': 10, 'রাত্রি': 11, 'বিদায়': 12, 'ধন্যবাদ': 13, 'দুঃখিত': 14, 'অনুগ্রহ': 15, 'করে': 16, 'হ্যাঁ': 17, 'না': 18, 'কেমন': 19, 'আমি': 20, 'ভালো': 21, 'আছি': 22, 'তোমার': 23, 'কী': 24, 'আমার': 25, 'দেবাশীষ': 26, 'কোথায়': 27, 'এখানে': 28, 'আসো': 29, 'বসো': 30, 'দাঁড়াও': 31, 'খোলো': 32, 'বন্ধ': 33, 'করো': 34}


In [ ]:
english_sequences = english_tokenizer.texts_to_sequences(
    english_sentences
)

bengali_sentences=decoder_bengali_sentences

bengali_sequences = bengali_tokenizer.texts_to_sequences(
    bengali_sentences
)

print(english_sequences)
print(bengali_sequences)


[[8], [9], [2, 10], [2, 11], [12], [13, 1], [14], [15], [16], [17], [18, 3, 1], [19, 20, 21], [22, 4, 23, 5], [24, 5, 4, 25], [26, 3, 1], [27, 28], [29, 30], [31, 32], [33, 6, 7], [34, 6, 7]]
[[1, 7, 2], [1, 8, 2], [1, 9, 2], [1, 10, 11, 2], [1, 12, 2], [1, 13, 2], [1, 14, 2], [1, 15, 16, 2], [1, 17, 2], [1, 18, 2], [1, 3, 19, 4, 2], [1, 20, 21, 22, 2], [1, 23, 5, 24, 2], [1, 25, 5, 26, 2], [1, 3, 27, 4, 2], [1, 28, 29, 2], [1, 30, 2], [1, 31, 2], [1, 6, 32, 2], [1, 6, 33, 34, 2]]


In [ ]:
 maximum_eng_length=0
 maximum_ben_length=0

for seq in english_sequences:
  maximum_eng_length=max(maximum_eng_length,len(seq))
print(maximum_eng_length)

for seq in bengali_sequences:
  maximum_ben_length=max(maximum_ben_length,len(seq))
print(maximum_ben_length)

4
5


In [ ]:
english_padded=pad_sequences(
    english_sequences,
    maxlen = maximum_eng_length,
    padding ='post'
)

bengali_padded=pad_sequences(
    bengali_sequences,
    maxlen = maximum_ben_length,
    padding ='post'
)

print(english_padded)
print(bengali_padded)

[[ 8  0  0  0]
 [ 9  0  0  0]
 [ 2 10  0  0]
 [ 2 11  0  0]
 [12  0  0  0]
 [13  1  0  0]
 [14  0  0  0]
 [15  0  0  0]
 [16  0  0  0]
 [17  0  0  0]
 [18  3  1  0]
 [19 20 21  0]
 [22  4 23  5]
 [24  5  4 25]
 [26  3  1  0]
 [27 28  0  0]
 [29 30  0  0]
 [31 32  0  0]
 [33  6  7  0]
 [34  6  7  0]]
[[ 1  7  2  0  0]
 [ 1  8  2  0  0]
 [ 1  9  2  0  0]
 [ 1 10 11  2  0]
 [ 1 12  2  0  0]
 [ 1 13  2  0  0]
 [ 1 14  2  0  0]
 [ 1 15 16  2  0]
 [ 1 17  2  0  0]
 [ 1 18  2  0  0]
 [ 1  3 19  4  2]
 [ 1 20 21 22  2]
 [ 1 23  5 24  2]
 [ 1 25  5 26  2]
 [ 1  3 27  4  2]
 [ 1 28 29  2  0]
 [ 1 30  2  0  0]
 [ 1 31  2  0  0]
 [ 1  6 32  2  0]
 [ 1  6 33 34  2]]


In [ ]:
english_vocab_size = len(english_tokenizer.word_index) + 1
bengali_vocab_size = len(bengali_tokenizer.word_index) + 1



In [ ]:
encoder_inputs = Input(shape=(maximum_eng_length,))

encoder_embedding = Embedding(
    input_dim = english_vocab_size,
    output_dim = 16,
)(encoder_inputs)

encode_lstm=LSTM(16,return_state=True)

encoder_outputs,state_h,state_c=encode_lstm(encoder_embedding)

encoder_states=[state_h,state_c]

In [ ]:
decoder_inputs=Input(shape=(maximum_ben_length-1,))

decoder_embedding_layer=Embedding(
    input_dim=bengali_vocab_size,
    output_dim=16)

decoder_lstm=LSTM(16,return_sequences=True,return_state=True)

decoder_outputs,_,_=decoder_lstm(decoder_embedding_layer(decoder_inputs),initial_state=encoder_states
)

decoder_dense=Dense(bengali_vocab_size,activation='softmax')

decoder_outputs=decoder_dense(decoder_outputs)

In [ ]:
model = Model(
    inputs=[encoder_inputs, decoder_inputs],
    outputs=decoder_outputs
)

In [ ]:
encoder_input_data = english_padded

decoder_input_data=bengali_padded[:, :-1]
decoder_target_data=bengali_padded[:,1:]

print(decoder_input_data)
print("----------------------------------------")
print(decoder_target_data)

[[ 1  7  2  0]
 [ 1  8  2  0]
 [ 1  9  2  0]
 [ 1 10 11  2]
 [ 1 12  2  0]
 [ 1 13  2  0]
 [ 1 14  2  0]
 [ 1 15 16  2]
 [ 1 17  2  0]
 [ 1 18  2  0]
 [ 1  3 19  4]
 [ 1 20 21 22]
 [ 1 23  5 24]
 [ 1 25  5 26]
 [ 1  3 27  4]
 [ 1 28 29  2]
 [ 1 30  2  0]
 [ 1 31  2  0]
 [ 1  6 32  2]
 [ 1  6 33 34]]
----------------------------------------
[[ 7  2  0  0]
 [ 8  2  0  0]
 [ 9  2  0  0]
 [10 11  2  0]
 [12  2  0  0]
 [13  2  0  0]
 [14  2  0  0]
 [15 16  2  0]
 [17  2  0  0]
 [18  2  0  0]
 [ 3 19  4  2]
 [20 21 22  2]
 [23  5 24  2]
 [25  5 26  2]
 [ 3 27  4  2]
 [28 29  2  0]
 [30  2  0  0]
 [31  2  0  0]
 [ 6 32  2  0]
 [ 6 33 34  2]]


In [ ]:
model = Model(
    inputs=[encoder_inputs, decoder_inputs],
    outputs=decoder_outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(
    [encoder_input_data, decoder_input_data],
    decoder_target_data,
    epochs=300,
    batch_size=4,
    verbose=1
)

Epoch 1/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.1500 - loss: 3.5511
Epoch 2/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.2500 - loss: 3.5376
Epoch 3/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.2500 - loss: 3.5237
Epoch 4/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2500 - loss: 3.5063 
Epoch 5/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2500 - loss: 3.4864 
Epoch 6/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2500 - loss: 3.4592 
Epoch 7/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2500 - loss: 3.4233
Epoch 8/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2500 - loss: 3.3733 
Epoch 9/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2500 - loss: 3.3090
Epoch 10/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2500 - loss: 3.2115 
Epoch 11/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2500 - loss: 3.0966 
Epoch 12/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2500 - los

In [ ]:
encoder_model = Model(
    inputs=encoder_inputs,
    outputs=encoder_states
)

In [ ]:
decoder_state_input_h = Input(shape=(16,))
decoder_state_input_c = Input(shape=(16,))

decoder_states_inputs = [
    decoder_state_input_h,
    decoder_state_input_c
]

In [ ]:
decoder_embedding_inf = decoder_embedding_layer(decoder_inputs)

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_embedding_inf,
    initial_state=decoder_states_inputs
)

decoder_states = [state_h, state_c]

decoder_outputs = decoder_dense(decoder_outputs)

In [ ]:
decoder_model = Model(
    inputs=[decoder_inputs] + decoder_states_inputs,
    outputs=[decoder_outputs] + decoder_states
)

In [ ]:
reverse_bengali = {
    index: word
    for word, index in bengali_tokenizer.word_index.items()
}

In [ ]:
import numpy as np

def translate(sentence):

    # ---------- Encoder ----------

    sequence = english_tokenizer.texts_to_sequences([sentence])

    sequence = pad_sequences(
        sequence,
        maxlen=maximum_eng_length,
        padding="post"
    )

    states = encoder_model.predict(sequence, verbose=0)

    # ---------- Decoder ----------

    target_seq = np.array(
        [[bengali_tokenizer.word_index["<start>"]]]
    )

    translated_sentence = []

    while True:

        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states,
            verbose=0
        )

        sampled_token = np.argmax(
            output_tokens[0, -1, :]
        )

        sampled_word = reverse_bengali.get(
            sampled_token,
            ""
        )

        if sampled_word == "<end>":
            break

        translated_sentence.append(sampled_word)

        target_seq = np.array([[sampled_token]])

        states = [h, c]

        if len(translated_sentence) > maximum_ben_length:
            break

    return " ".join(translated_sentence)

In [ ]:
print(translate("hello"))
print(translate("good morning"))
print(translate("thank you"))
print(translate("i am fine"))
print(translate("where are you"))

হ্যালো
সুপ্রভাত
ধন্যবাদ
আমি ভালো আছি
তুমি কোথায় আছো


In [ ]:
print(translate("i am debasish"))

আমি ভালো আছি


In [ ]:
print(translate("i am debasish"))
print(translate("hello goodbye"))
print(translate("please come here"))
print(translate("how are you"))

আমি ভালো আছি
হ্যালো
এখানে আসো
তুমি কেমন আছো
